# Setup
name:         docs4IT
creator:      Sierk Hoeksma
creator_url:  https://sjhoeksma.github.com 
about_img:  /img/clouddocs.jpeg
title:        docs4IT
description:  A collections of documents which can be handy for ITHow to do Cloud
email: 	      info@docs4.it
locale:       "en"
timezone:     Europe/Amsterdam
baseurl:      ""
url: 					"https://sjhoeksma.github.io" # the base hostname & protocol for your site
repository:   "http://github.com/sjhoeksma/sjhoeksma.github.io" 
usesidemenu: true  #When put to true site menu is shown in posts and header removed
showProgressBar: 1 #Time in minutes when progressbar shoud be shown

# The algolia search engine
#algolia:
#  application_id: '0DX4FSFFQY'
#  index_name:     'doc4it'
#  search_only_api_key: '6ab3a2fe1b9e6a97c87f7e8824c7f3a4'

# google_analytics: "UA-XXXXXXXX-X" # Add you google_analytics id if neede

#Default values
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Gems
plugins:
- jemoji
# - jekyll-minifier

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:name/

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Print
    url: /print/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Compress the stylesheets		
sass:
  style: compressed		
 
 
# Collection Directory
collections:
  - principles
  - framework
  - mof
  - roles
  - kpi
  
 
collections:
  principles:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /:collection/:name
  framework:
    output: true
    permalink: /:collection/:name
  mof:
    output: true
    permalink: /:collection/:name
  roles:
    output: true
    permalink: /:collection/:name
  kpi:
    output: true
    permalink: /:collection/:name  
    
    
  
  
# User Settings
username: docs4IT
user_description: docs4IT.
disqus_username: cf_username

# Social Media
# Remove the item if you don't need it
#github_username: github_username
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

