# Setup
name:         Cloud Docs
creator:      Sierk Hoeksma
creator_url:  https://sjhoeksma.github.com 
about_img:  /img/clouddocs.jpeg
title:        CloudDocs
description:  How to do Cloud
email: 	      sjhoeksma@gmail.com
locale:       "en"
timezone:     Europe/Amsterdam
baseurl:      ""
url: 					"https://sjhoeksma.github.io" # the base hostname & protocol for your site
repository:   "http://github.com/sjhoeksma/sjhoeksma.github.io" 
usesidemenu: true  #When put to true site menu is shown in posts and header removed
showProgressBar: 1 #Time in minutes when progressbar shoud be shown

# The algolia search engine
#algolia:
#  application_id: '0DX4FSFFQY'
#  index_name:     'clouddocs'
#  search_only_api_key: '6ab3a2fe1b9e6a97c87f7e8824c7f3a4'

# google_analytics: "UA-XXXXXXXX-X" # Add you google_analytics id if neede

# Gems
plugins:
- jemoji
# - jekyll-minifier

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:name/

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Compress the stylesheets		
sass:
  style: compressed		
 
 
# Collection Directory
collections:
  - principles
  - framework
  
 
collections:
  principles:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /:collection/:name
  framework:
    output: true
    permalink: /:collection/:name
  
  
# User Settings
username: CloudDocs
user_description: Cloud Docs.
disqus_username: cf_username

# Social Media
# Remove the item if you don't need it
#github_username: github_username
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

