# Setup
name:         Cloud@Work
tagline:      How can we serve
timezone:     Europe/Berlin
baseurl:      ""
locale:       "en"
repository:   http://github.com/sjhoeksma/sjhoeksma.github.io

#Others
markdown: kramdown

# Gems
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-redirect-from
- jemoji
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-avatar