# Setup
name:         CloudDocs
creator:      Sierk Hoeksma
creator_url:  https://sjhoeksma.github.com 
creator_img:  https://avatars3.githubusercontent.com/u/5503837?s=460&v=4
title:        CloudDocs
description:  How to do Cloud
email: 	      sjhoeksma@gmail.com
locale:       "en"
timezone:     Europe/Amsterdam
baseurl:      ""
url: 					"https://sjhoeksma.github.io" # the base hostname & protocol for your site
repository:   "http://github.com/sjhoeksma/sjhoeksma.github.io" 
usenavigation: false
# google_analytics: "UA-XXXXXXXX-X" # Add you google_analytics id if neede

# Gems
plugins:
- jemoji
- jekyll-mermaid
# - jekyll-minifier

# Mermaid let's you draw graphs: https://github.com/knsv/mermaid

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Compress the stylesheets		
sass:
  style: compressed		
 
 
# Collection Directory
collections:
  - topics
 
collections:
  topics:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /:collection/:name
  
  
# User Settings
username: CloudDocs
user_description: Cloud Docs.
disqus_username: cf_username

# Social Media
# Remove the item if you don't need it
#github_username: github_username
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

